channels:
  - nicolasradomski
  - conda-forge
  - defaults

package:
  name: genomicbasedregression
  version: "1.1.0"

source:
  path: .

build:
  number: 0
  script: |
    mkdir -p "$PREFIX/bin"
    cp "$SRC_DIR/GenomicBasedRegression.py" "$PREFIX/bin/GenomicBasedRegression.py"
    echo '#!/bin/bash' > "$PREFIX/bin/genomicbasedregression"
    echo 'python "$CONDA_PREFIX/bin/GenomicBasedRegression.py" "$@"' >> "$PREFIX/bin/genomicbasedregression"
    chmod +x "$PREFIX/bin/genomicbasedregression"

requirements:
  host:
    - python=3.12
    - pip
  run:
    - python=3.12
    - catboost==1.2.8
    - pandas==2.2.2
    - xgboost==2.1.3
    - lightgbm==4.6.0
    - boruta==0.4.3
    - scipy==1.16.0
    - scikit-learn==1.5.2
    - numpy==1.26.4
    - joblib==1.5.1
    - tqdm==4.67.1
    - tqdm-joblib==0.0.4

about:
  home: "https://github.com/Nicolas-Radomski/GenomicBasedRegression"
  summary: "Script performing regression-based modeling or prediction from genomic data"
  license: "GPL-3.0"

extra:
  recipe-maintainers:
    - Nicolas-Radomski

test:
  commands:
    - python -c "import catboost, pandas, xgboost, lightgbm, boruta, scipy, sklearn, numpy, joblib, tqdm, tqdm_joblib; print('Test successful')"
    - python "$CONDA_PREFIX/bin/GenomicBasedRegression.py" --help
    - genomicbasedregression --help
